# Generated by Django 6.0.5 on 2026-06-05 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Simulado Gerado', max_length=200)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulados', to=settings.AUTH_USER_MODEL)),
                ('questoes', models.ManyToManyField(related_name='simulados_presentes', to='core.questao')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.TextField(blank=True, null=True)),
                ('esta_correta', models.BooleanField(default=False)),
                ('alternativa_marcada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questao')),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.simulado')),
            ],
        ),
    ]
