# Generated by Django 6.0.5 on 2026-06-15 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_simulado_respostaaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='turmas_como_aluno', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(limit_choices_to={'is_professor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='turmas_como_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
