# Generated by Django 6.0.5 on 2026-06-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_simulado_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='is_publica',
            field=models.BooleanField(default=True),
        ),
    ]
